# argument to provide specific version of qie node
ARG INITIAL_VERSION
# checkov:skip=CKV_DOCKER_3:No need to create a user, this is only used on tests
FROM tharsishq/qie:$INITIAL_VERSION

WORKDIR /go/src/github.com/qie/qie

COPY ./init-node.sh .

# JSON-RPC server
EXPOSE 8545

HEALTHCHECK CMD curl --fail http://localhost:26657 || exit 1

CMD ["sh", "./init-node.sh"]
